set(TARGET_PLATFORM "rk3568" CACHE STRING "Target platform")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc CACHE FILEPATH "RK3568 C compiler")
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++ CACHE FILEPATH "RK3568 C++ compiler")

set(RK3568_SYSROOT "" CACHE PATH "Optional RK3568 sysroot")
if(RK3568_SYSROOT)
    set(CMAKE_SYSROOT "${RK3568_SYSROOT}")
    list(APPEND CMAKE_FIND_ROOT_PATH "${RK3568_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
