set(TARGET_PLATFORM "t113" CACHE STRING "Target platform")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc CACHE FILEPATH "T113 C compiler")
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++ CACHE FILEPATH "T113 C++ compiler")

set(T113_SYSROOT "" CACHE PATH "Optional T113 sysroot")
if(T113_SYSROOT)
    set(CMAKE_SYSROOT "${T113_SYSROOT}")
    list(APPEND CMAKE_FIND_ROOT_PATH "${T113_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
